title: Radar Data Cookbook
author: ARM Development Team
logo: images/arm_logo.png
execute:
  execute_notebooks: "off"
parse:
  myst_enable_extensions:
    - html_image
html:
  comments:
    hypothesis: true
launch_buttons:
  jupyterhub_url: "https://jupyterhub.arm.gov"